rwo:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: de-project-418719
      dataset: rwo_dataset
      threads: 4 # Must be a value of 1 or greater
      keyfile: "/home/src/de-project-terraform.json"
      location: australia-southeast2